/*
   The MIT License (MIT)

   Copyright (c) 2014

   Permission is hereby granted, free of charge, to any person obtaining a copy of
   this software and associated documentation files (the "Software"), to deal in
   the Software without restriction, including without limitation the rights to
   use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
   the Software, and to permit persons to whom the Software is furnished to do so,
   subject to the following conditions:

   The above copyright notice and this permission notice shall be included in all
   copies or substantial portions of the Software.

   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
   FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
   COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
   IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
   CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

#include "cibutil.h"
#include "cibidmgr.h"
#include "cibfunction_helper.h"
#include "cibcompound.h"
#include "cibfunction.h"

#include "cppparser.h"

#include <boost/tokenizer.hpp>

#include <ostream>

//////////////////////////////////////////////////////////////////////////

void CibIdMgr::assignIds(const CppProgramEx& expProg, const CibParams& cibParams)
{
  // First create Ids for global functions
  const CppCompoundArray& fileDOMs = expProg.getProgram().getFileDOMs();
  for (auto fileCmpound : fileDOMs)
  {
    assignIds(static_cast<const CibCppCompound*>(fileCmpound), cibParams);
  }
}

void CibIdMgr::assignIds(const CibCppCompound* compound, const CibParams& cibParams)
{
  for (auto mem : compound->members_)
  {
    if (isMemberPublic(mem->prot_, compound->compoundType_) && mem->isNamespaceLike())
    {
      assignIds(static_cast<const CibCppCompound*>(mem), cibParams);
    }
  }

  if (compound->getNeedsBridgingMethods().empty())
    return;

  auto itr = cibIdTable_.find(compound->fullName());
  if (itr == cibIdTable_.end())
  {
    auto classIdName = compound->fullName();
    std::transform(classIdName.begin(), classIdName.end(), classIdName.begin(), [](char c)->char {
      return c == ':' ? '_' : c;
    });
    itr = cibIdTable_.emplace(std::make_pair(compound->fullName(), CibIdData(classIdName, nextClassId_++))).first;
  }
  auto& cibIdData = itr->second;
  auto&& methodIdTable = cibIdData.getMethodIdTable();
  for (auto& func : compound->getNeedsBridgingMethods())
  {
    auto&& sig = func.signature();
    auto methodItr = methodIdTable.find(sig);
    if (methodItr == methodIdTable.end())
    {
      cibIdData.addMethod(sig, func.capiName(cibParams));
    }
  }

  compound->forEachParent(kPublic, [compound, &cibIdData, &cibParams](auto parent) {
    auto castMethodName = compound->castToBaseName(parent, cibParams);
    cibIdData.addMethod(castMethodName, castMethodName);
  });
}

/*!
 * @return "namespace X { namespace Y {" for X::Y as input.
 */
static std::string expandNs(std::string::const_iterator beg, std::string::const_iterator end)
{
  if (beg == end)
    return std::string();
  if (*beg == ':')
    return expandNs(beg + 2, end);
  auto itr = std::adjacent_find(beg, end, [](auto c1, auto c2)->bool {
    return c1 == c2 && c1 == ':';
  });

  auto expanded = std::string("namespace ") + std::string(beg, itr) + " {";
  if (itr == end)
    return expanded;
  else
    return expanded + std::string(" ") + expandNs(itr + 2, end);
}

/*!
* @return "}}" for X::Y as input.
* @sa expandNs.
*/
static std::string closingNs(std::string::const_iterator beg, std::string::const_iterator end)
{
  if (beg == end)
    return std::string();
  if (*beg == ':')
    return closingNs(beg + 2, end);
  auto itr = std::adjacent_find(beg, end, [](auto c1, auto c2)->bool {
    return c1 == c2 && c1 == ':';
  });
  std::string closingBraces = "}";
  if (itr == end)
    return closingBraces;
  else
    return closingBraces + closingNs(itr + 2, end);
}

bool CibIdMgr::saveIds(const std::string& idsFilePath, const CibParams& cibParams) const
{
  std::ofstream stm(idsFilePath, std::ios_base::out);
  stm << "// DO NOT EDIT THIS FILE\n\n";
  stm << "#pragma once\n\n";
  CppIndent indentation;
  stm << "namespace __zz_cib_ { namespace " << cibParams.moduleName << "Lib {\n";
  stm << ++indentation << "namespace __zz_cib_classid {\n";
  stm << ++indentation << "enum {\n";
  ++indentation;
  for (const auto& cls : cibIdTable_)
  {
    const auto& fullName = cls.first;
    const auto& cibIdData = cls.second;
    stm << indentation << "//#= " << fullName << "\n";
    stm << indentation << cibIdData.getIdName() << " = " << cibIdData.getId() << ",\n";
  }
  stm << indentation << "__zz_cib_next_class_id = " << nextClassId_ << "\n";
  stm << --indentation << "};\n";
  stm << --indentation << "}\n";
  stm << --indentation << "}}\n\n";

  for (const auto& cls : cibIdTable_)
  {
    const auto& classIdName = cls.first;
    const auto& cibIdData = cls.second;
    stm << "namespace __zz_cib_ {\n";
    stm << ++indentation << expandNs(classIdName.begin(), classIdName.end()) << '\n';
    stm << ++indentation << "namespace __zz_cib_methodid {\n";
    stm << ++indentation << "enum {\n";
    ++indentation;
    for (const auto& methodId : cls.second.getMethodIdTable())
    {
      stm << indentation << "//#= " << methodId.first << '\n';
      stm << indentation << methodId.second.second << " = " << methodId.second.first << ",\n";
    }
    stm << indentation << "__zz_cib_next_method_id = " << cls.second.getNextMethodId() << '\n';
    stm << --indentation << "};\n";
    stm << --indentation << "}\n";
    stm << --indentation << closingNs(classIdName.begin(), classIdName.end()) << '\n';
    stm << --indentation << "}\n";
  }
  return true;
}
