/*
    Generated by cib for ABI compatibility and stability.
    For copyright details refer to the copyright statement of library that contains this file.
*/

#pragma once

namespace __zz_cib_ {

template <typename>
class __zz_cib_Generic
{
};

} // namespace __zz_cib_
