// This file will be generated by cib tool when run for a library
// Below is the what it should contain.

// Assume somewhere in library headers there are definitions like:
// ex1
class A
{
};
// ex2
namespace N {
class B
{
};
} // namespace N
// ex3
struct C
{
};

// Then below should be it's content.

#ifndef __ZZ_CIB_CLASS_THAT_USES_METHOD_TABLE
#  define __ZZ_CIB_CLASS_THAT_USES_METHOD_TABLE(fullClassName)
#endif
#ifndef __ZZ_CIB_CLASS_THAT_SHARES_LAYOUT
#  define __ZZ_CIB_CLASS_THAT_SHARES_LAYOUT(fullClassName)
#endif

__ZZ_CIB_CLASS_THAT_USES_METHOD_TABLE(A)
__ZZ_CIB_CLASS_THAT_USES_METHOD_TABLE(N::B)
__ZZ_CIB_CLASS_THAT_USES_METHOD_TABLE(C)

__ZZ_CIB_CLASS_THAT_SHARES_LAYOUT(C)

#undef __ZZ_CIB_CLASS_THAT_USES_METHOD_TABLE
#undef __ZZ_CIB_CLASS_THAT_SHARES_LAYOUT
