/////////////////////////////////////////////////////////////////////////////
// WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING //
// This file is generated by CIB and should not be edited.
// If CIB is run again the edited changes will go away forever.
/////////////////////////////////////////////////////////////////////////////

#include "$CIBIDHDR$"
#include <cstdint>

/**
 * Returns address of above declared APIs
 * This library must have a way to let client call this API
 * This is kind of a hook that client needs to use all methods and classes that this library wants to expose.
 */
extern "C" $CIBEXPAPI$ void __stdcall __zz_cib_$MODULE$LibGetMethodTable(std::uint32_t methodId)
{
   switch(methodId)
   {
   case 0: return (void*) _cib_::$MODULE$Lib::CtoCpp::MetaInterface::GetMetaInterface;
   case 1: return (void*) _cib_::$MODULE$Lib::CtoCpp::MetaInterface::AddMethod;
   case 2: return (void*) _cib_::$MODULE$Lib::CtoCpp::MetaInterface::GetMethod;
   }
   return 0;
}

//////////////////////////////////////////////////////////////////////////
