// DO NOT EDIT THIS FILE

#ifndef __CIBID_ShapeLib_H__
#define __CIBID_ShapeLib_H__

namespace _cib_ { namespace ShapeLib {
	namespace Geometry {
		enum {
			//#= class Circle;
			kCIBID_Circle = 6,
			//#= class Composite;
			kCIBID_Composite = 16,
			//#= class Rectangle;
			kCIBID_Rectangle = 22,
			//#= class Shape;
			kCIBID_Shape = 27,
		};
		namespace Circle {
			enum {
				//#= Circle(int Ox, int Oy, int radius);
				kCIBID___new = 1,
				//#= __cast_to_Geometry__Shape();
				kCIBID___cast_to_Geometry__Shape = 5,
				//#= virtual double Area() const;
				kCIBID_Area = 2,
				//#= virtual double Perimeter() const;
				kCIBID_Perimeter = 3,
				//#= virtual void Draw(HDC hdc) const;
				kCIBID_Draw = 4,
			};
		}
		namespace Composite {
			enum {
				//#= Composite();
				kCIBID___new = 7,
				//#= Shape* ShapeAt(size_t idxShape) const;
				kCIBID_ShapeAt = 10,
				//#= __cast_to_Geometry__Shape();
				kCIBID___cast_to_Geometry__Shape = 15,
				//#= size_t NumShapes() const;
				kCIBID_NumShapes = 9,
				//#= static Composite* CreateCompositeOfRectAndCircle();
				kCIBID_CreateCompositeOfRectAndCircle = 14,
				//#= virtual double Area() const;
				kCIBID_Area = 11,
				//#= virtual double Perimeter() const;
				kCIBID_Perimeter = 12,
				//#= virtual void Draw(HDC hdc) const;
				kCIBID_Draw = 13,
				//#= void Add(Shape* shape);
				kCIBID_Add = 8,
			};
		}
		namespace Rectangle {
			enum {
				//#= Rectangle(int left, int top, int right, int bottom);
				kCIBID___new = 17,
				//#= __cast_to_Geometry__Shape();
				kCIBID___cast_to_Geometry__Shape = 21,
				//#= virtual double Area() const;
				kCIBID_Area = 18,
				//#= virtual double Perimeter() const;
				kCIBID_Perimeter = 19,
				//#= virtual void Draw(HDC hdc) const;
				kCIBID_Draw = 20,
			};
		}
		namespace Shape {
			enum {
				//#= virtual double Area() const /*= 0*/;
				kCIBID_Area = 23,
				//#= virtual double Perimeter() const /*= 0*/;
				kCIBID_Perimeter = 24,
				//#= virtual void Draw(HDC hdc) const /*= 0*/;
				kCIBID_Draw = 25,
				//#= virtual ~Shape();
				kCIBID___delete = 26,
			};
		}
	}
}}

#endif
