// DO NOT EDIT THIS FILE

#pragma once

namespace __zz_cib_ { namespace GraphicsLib {
	namespace __zz_cib_classid {
		enum {
			//#= ::Graphics::Circle
			__Graphics__Circle = 1,
			//#= ::Graphics::ContextLogger
			__Graphics__ContextLogger = 4,
			//#= ::Graphics::Context
			__Graphics__Context = 3,
			//#= ::Graphics::Composite
			__Graphics__Composite = 2,
			//#= ::Graphics::Shape
			__Graphics__Shape = 6,
			//#= ::Graphics::Rectangle
			__Graphics__Rectangle = 5,
			__zz_cib_next_class_id = 7
		};
	}
}}

namespace __zz_cib_ {
	namespace Graphics { namespace Circle {
		namespace __zz_cib_methodid {
			enum {
				//#= Circle(floatfloat Ox, floatfloat Oy, floatfloat radius);
				__zz_cib_new1 = 1,
				//#= virtual float Area() const;
				Area2 = 2,
				//#= virtual float Perimeter() const;
				Perimeter3 = 3,
				//#= virtual void Draw(Context*Context* ctx) const;
				Draw4 = 4,
				//#= __zz_cib_cast_to___Graphics__Shape
				__zz_cib_cast_to___Graphics__Shape5 = 5,
				__zz_cib_next_method_id = 6
			};
		}
	}}
}
namespace __zz_cib_ {
	namespace Graphics { namespace ContextLogger {
		namespace __zz_cib_methodid {
			enum {
				//#= ContextLogger();
				__zz_cib_new1 = 1,
				//#= ~ContextLogger()
				__zz_cib_delete2 = 2,
				//#= virtual void Move(floatfloat x, floatfloat y);
				Move3 = 3,
				//#= virtual void Line(floatfloat x, floatfloat y);
				Line4 = 4,
				//#= virtual void Curve(floatfloat x1, floatfloat y1, floatfloat x2, floatfloat y2, floatfloat x3, floatfloat y3);
				Curve5 = 5,
				//#= virtual void Close();
				Close6 = 6,
				//#= __zz_cib_cast_to___Graphics__Context
				__zz_cib_cast_to___Graphics__Context7 = 7,
				__zz_cib_next_method_id = 8
			};
		}
	}}
}
namespace __zz_cib_ {
	namespace Graphics { namespace Context {
		namespace __zz_cib_methodid {
			enum {
				//#= ~Context()
				__zz_cib_delete1 = 1,
				__zz_cib_next_method_id = 2
			};
		}
	}}
}
namespace __zz_cib_ {
	namespace Graphics { namespace Composite {
		namespace __zz_cib_methodid {
			enum {
				//#= Composite();
				__zz_cib_new1 = 1,
				//#= void Add(Shape*Shape* shape);
				Add2 = 2,
				//#= size_t NumShapes() const;
				NumShapes3 = 3,
				//#= Shape* ShapeAt(size_tsize_t idxShape) const;
				ShapeAt4 = 4,
				//#= virtual float Area() const;
				Area5 = 5,
				//#= virtual float Perimeter() const;
				Perimeter6 = 6,
				//#= virtual void Draw(Context*Context* ctx) const;
				Draw7 = 7,
				//#= static Composite* CreateCompositeOfRectAndCircle();
				CreateCompositeOfRectAndCircle8 = 8,
				//#= __zz_cib_cast_to___Graphics__Shape
				__zz_cib_cast_to___Graphics__Shape9 = 9,
				__zz_cib_next_method_id = 10
			};
		}
	}}
}
namespace __zz_cib_ {
	namespace Graphics { namespace Shape {
		namespace __zz_cib_methodid {
			enum {
				//#= ~Shape()
				__zz_cib_delete1 = 1,
				__zz_cib_next_method_id = 2
			};
		}
	}}
}
namespace __zz_cib_ {
	namespace Graphics { namespace Rectangle {
		namespace __zz_cib_methodid {
			enum {
				//#= Rectangle(floatfloat left, floatfloat top, floatfloat right, floatfloat bottom);
				__zz_cib_new1 = 1,
				//#= virtual float Area() const;
				Area2 = 2,
				//#= virtual float Perimeter() const;
				Perimeter3 = 3,
				//#= virtual void Draw(Context*Context* ctx) const;
				Draw4 = 4,
				//#= __zz_cib_cast_to___Graphics__Shape
				__zz_cib_cast_to___Graphics__Shape5 = 5,
				__zz_cib_next_method_id = 6
			};
		}
	}}
}
