/*
    Generated by cib for ABI compatibility and stability.
    For copyright details refer to the copyright statement of library that contains this file.
*/

#pragma once

#define __ZZ_CIB_DECLARE_VALUE_CLASS(className)                                                                        \
  namespace __zz_cib_ {                                                                                                \
  template <>                                                                                                          \
  struct __zz_cib_IsValueType<className> : std::true_type                                                              \
  {                                                                                                                    \
  };                                                                                                                   \
  } // namespace __zz_cib_

#include "example.h"
__ZZ_CIB_DECLARE_VALUE_CLASS(::Pod)
