/////////////////////////////////////////////////////////////////////////////
// WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING //
// This file is generated by CIB and should not be edited.
// If CIB is run again the edited changes will go away forever.
/////////////////////////////////////////////////////////////////////////////

#pragma once

#include <cstdint>
#include <cstddef>

#ifndef __zz_cib_decl
# ifdef __GNUC__
#   define __zz_cib_decl __attribute__((stdcall))
# elif defined(_WIN32)
#   define __zz_cib_decl __stdcall
# endif
#endif

#ifndef __zz_cib_export
# if defined _WIN32 || defined __CYGWIN__
#   ifdef __GNUC__
#     define __zz_cib_export __attribute__ ((dllexport))
#   else
#     define __zz_cib_export __declspec(dllexport)
#   endif
# else
#   if __GNUC__ >= 4
#     define __zz_cib_export __attribute__ ((visibility ("default")))
#   else
#     define __zz_cib_export
#   endif
# endif
#endif

namespace __zz_cib_ {
  class PROXY;
  struct MethodTableHeader {
    size_t size; //!< sizeof(MethodTableHeader)
    size_t numMethods; //!< Number of methods in method table.
  };
  using MethodEntry = void(*)();
  using MethodTable = const MethodEntry*;
}
