/////////////////////////////////////////////////////////////////////////////
// WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING //
// This file is generated by CIB and should not be edited.
// If CIB is run again the edited changes will go away forever.
/////////////////////////////////////////////////////////////////////////////

#pragma once

#include <cstdint>

namespace __zz_cib_ {
  class PROXY;
  using MethodEntry = void(*)();
  using MethodTable = const MethodEntry*;

  void GraphicsLib_GetMethodTable(std::uint32_t classId, MethodTable* pMethodTable, std::uint32_t* pLen);
}
