// DO NOT EDIT THIS FILE

#pragma once

namespace __zz_cib_ { namespace PerfTestLib {
	namespace __zz_cib_classid {
		enum {
			//#= ::FuncCallClass
			__FuncCallClass = 1,
			__zz_cib_next_class_id = 2
		};
	}
}}

namespace __zz_cib_ {
	namespace FuncCallClass {
		namespace __zz_cib_methodid {
			enum {
				//#= static void SimplestFunc();
				SimplestFunc_1 = 1,
				//#= void SimplestMethod();
				SimplestMethod_2 = 2,
				//#= double FuncWith3Param(int, double, float);
				FuncWith3Param_3 = 3,
				//#= FuncCallClass();
				__zz_cib_new_4 = 4,
				__zz_cib_next_method_id = 5
			};
		}
	}
}
