// DO NOT EDIT THIS FILE

#pragma once

namespace __zz_cib_ { namespace Example { namespace A {
  //#= FullClassName: ::Example::A
  enum { __zz_cib_classid = 2 };
}}}

namespace __zz_cib_ { namespace Example { namespace __zz_cib_Class1 {
  //#= FullClassName: ::Example::Template<int>
  enum { __zz_cib_classid = 1 };
}}}

namespace __zz_cib_ { namespace Example {
  enum { __zz_cib_next_class_id = 3 };
}}

namespace __zz_cib_ { namespace Example { namespace A { namespace __zz_cib_methodid {
  enum {
    //#= A(const ::Example::A&);
    __zz_cib_copy_0 = 0,
    //#= ~A();
    __zz_cib_delete_1 = 1,
    //#= A();
    __zz_cib_new_2 = 2,
    //#= void Set(const ::Example::Template<int>&);
    Set_3 = 3,
    //#= const ::Example::Template<int>& Get() const;
    Get_4 = 4,
    __zz_cib_next_method_id = 5
  };
}}}}

namespace __zz_cib_ { namespace Example { namespace __zz_cib_Class1 { namespace __zz_cib_methodid {
  enum {
    //#= Template(const ::Example::Template<int>&);
    __zz_cib_new_0 = 0,
    //#= ~Template();
    __zz_cib_delete_1 = 1,
    //#= Template(int);
    __zz_cib_new_2 = 2,
    //#= int GetX() const;
    GetX_3 = 3,
    __zz_cib_next_method_id = 4
  };
}}}}

