/*
    Generated by cib for ABI compatibility and stability.
*/

#pragma once

namespace __zz_cib_ {

/**
 * Helpful in taking away the dirty details of implementing methods of a proxy class.
 * The second parameter is only used as a trick to delay the specialization of __zz_cib_Helper until it is actually
 * needed.
 */
template <typename _ProxyClass, typename _SpecializationDelayer = _ProxyClass>
struct __zz_cib_Helper
{
};

} // namespace __zz_cib_
