// DO NOT EDIT THIS FILE

#pragma once

namespace __zz_cib_ { namespace __zz_cib_classid {
	enum {
		//#= ::Example::A
		__Example__A = 1,
		__zz_cib_next_class_id = 2
	};
}}

namespace __zz_cib_ { namespace Example { namespace A { namespace __zz_cib_methodid {
	enum {
		//#= void SomeFunc();
		SomeFunc_1 = 1,
		//#= A();
		__zz_cib_new_2 = 2,
		//#= ~A()
		__zz_cib_delete_3 = 3,
		__zz_cib_next_method_id = 4
	};
}}}}

