// DO NOT EDIT THIS FILE

#ifndef __CIBID_GraphicsLib_H__
#define __CIBID_GraphicsLib_H__

namespace _cib_ { namespace GraphicsLib {
	namespace Graphics {
		enum {
			//#= class Circle;
			kCIBID_Circle = 6,
			//#= class Composite;
			kCIBID_Composite = 16,
			//#= class Context;
			kCIBID_Context = 21,
			//#= class ContextLogger;
			kCIBID_ContextLogger = 28,
			//#= class Rectangle;
			kCIBID_Rectangle = 34,
			//#= class Shape;
			kCIBID_Shape = 39,
		};
		namespace Circle {
			enum {
				//#= Circle(float Ox, float Oy, float radius);
				kCIBID___new = 1,
				//#= __cast_to_Graphics__Shape();
				kCIBID___cast_to_Graphics__Shape = 5,
				//#= virtual float Area() const;
				kCIBID_Area = 2,
				//#= virtual float Perimeter() const;
				kCIBID_Perimeter = 3,
				//#= virtual void Draw(Context* ctx) const;
				kCIBID_Draw = 4,
			};
		}
		namespace Composite {
			enum {
				//#= Composite();
				kCIBID___new = 7,
				//#= Shape* ShapeAt(size_t idxShape) const;
				kCIBID_ShapeAt = 10,
				//#= __cast_to_Graphics__Shape();
				kCIBID___cast_to_Graphics__Shape = 15,
				//#= size_t NumShapes() const;
				kCIBID_NumShapes = 9,
				//#= static Composite* CreateCompositeOfRectAndCircle();
				kCIBID_CreateCompositeOfRectAndCircle = 14,
				//#= virtual float Area() const;
				kCIBID_Area = 11,
				//#= virtual float Perimeter() const;
				kCIBID_Perimeter = 12,
				//#= virtual void Draw(Context* ctx) const;
				kCIBID_Draw = 13,
				//#= void Add(Shape* shape);
				kCIBID_Add = 8,
			};
		}
		namespace Context {
			enum {
				//#= virtual void Close() = 0;
				kCIBID_Close = 20,
				//#= virtual void Curve(float x1, float y1, float x2, float y2, float x3, float y3) = 0;
				kCIBID_Curve = 19,
				//#= virtual void Line(float x, float y) = 0;
				kCIBID_Line = 18,
				//#= virtual void Move(float x, float y) = 0;
				kCIBID_Move = 17,
			};
		}
		namespace ContextLogger {
			enum {
				//#= ContextLogger();
				kCIBID___new = 22,
				//#= __cast_to_Graphics__Context();
				kCIBID___cast_to_Graphics__Context = 27,
				//#= virtual void Close();
				kCIBID_Close = 26,
				//#= virtual void Curve(float x1, float y1, float x2, float y2, float x3, float y3);
				kCIBID_Curve = 25,
				//#= virtual void Line(float x, float y);
				kCIBID_Line = 24,
				//#= virtual void Move(float x, float y);
				kCIBID_Move = 23,
			};
		}
		namespace Rectangle {
			enum {
				//#= Rectangle(float left, float top, float right, float bottom);
				kCIBID___new = 29,
				//#= __cast_to_Graphics__Shape();
				kCIBID___cast_to_Graphics__Shape = 33,
				//#= virtual float Area() const;
				kCIBID_Area = 30,
				//#= virtual float Perimeter() const;
				kCIBID_Perimeter = 31,
				//#= virtual void Draw(Context* ctx) const;
				kCIBID_Draw = 32,
			};
		}
		namespace Shape {
			enum {
				//#= virtual float Area() const = 0;
				kCIBID_Area = 35,
				//#= virtual float Perimeter() const = 0;
				kCIBID_Perimeter = 36,
				//#= virtual void Draw(Context* ctx) const = 0;
				kCIBID_Draw = 37,
				//#= virtual ~Shape();
				kCIBID___delete = 38,
			};
		}
	}
}}

#endif
