SET(PODOFO_CIB_SOURCES
${PoDoFo_SOURCE_DIR}/cib/__zz_cib_bidirectional_iterator.h.cpp
${PoDoFo_SOURCE_DIR}/cib/__zz_cib_bidirectional_reverse_iterator.h.cpp
${PoDoFo_SOURCE_DIR}/cib/__zz_cib_CibPoDoFo-gateway.cpp
${PoDoFo_SOURCE_DIR}/cib/list.cpp
${PoDoFo_SOURCE_DIR}/cib/__zz_cib_vector-reverse_iterator.h.cpp
${PoDoFo_SOURCE_DIR}/cib/__zz_cib_vector-iterator.h.cpp
${PoDoFo_SOURCE_DIR}/cib/vector.cpp
${PoDoFo_SOURCE_DIR}/cib/__zz_cib_PoDoFo.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/podofo.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/doc/PdfField.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/doc/PdfTable.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/doc/PdfOutlines.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/doc/PdfFontMetricsFreetype.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/doc/PdfSignOutputDevice.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/doc/PdfPage.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/doc/PdfShadingPattern.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/doc/PdfFontTrueType.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/doc/PdfSignatureField.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/doc/PdfFontMetrics.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/doc/PdfAcroForm.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/doc/PdfFontMetricsBase14.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/doc/PdfFontType1.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/doc/PdfFontMetricsObject.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/doc/PdfFontType3.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/doc/PdfIdentityEncoding.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/doc/PdfAnnotation.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/doc/PdfFontTTFSubset.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/doc/PdfFontFactoryBase14Data.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/doc/PdfStreamedDocument.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/doc/PdfCMapEncoding.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/doc/PdfPagesTreeCache.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/doc/PdfNamesTree.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/doc/PdfDocument.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/doc/PdfPainter.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/doc/PdfPainterMM.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/doc/PdfHintStream.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/doc/PdfDifferenceEncoding.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/doc/PdfImage.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/doc/PdfXObject.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/doc/PdfFontType1Base14.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/doc/PdfElement.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/doc/PdfMemDocument.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/doc/PdfFontConfigWrapper.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/doc/PdfAction.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/doc/PdfFontSimple.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/doc/PdfExtGState.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/doc/PdfFont.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/doc/PdfFontCache.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/doc/PdfTilingPattern.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/doc/PdfFunction.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/doc/PdfFontFactory.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/doc/PdfDestination.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/doc/PdfInfo.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/doc/PdfEncodingObjectFactory.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/doc/PdfPagesTree.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/doc/PdfFontCID.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/doc/PdfContents.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/doc/PdfFileSpec.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/podofo-base.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/base/PdfDefines.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/base/PdfEncrypt.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/base/PdfParser.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/base/PdfOwnedDataType.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/base/PdfVariant.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/base/PdfVecObjects.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/base/PdfObjectStreamParserObject.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/base/PdfRefCountedBuffer.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/base/PdfMemoryManagement.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/base/PdfInputStream.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/base/PdfInputDevice.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/base/Pdf3rdPtyForwardDecl.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/base/PdfContentsTokenizer.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/base/PdfLocale.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/base/PdfParserObject.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/base/PdfOutputDevice.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/base/PdfCanvas.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/base/PdfObject.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/base/PdfName.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/base/PdfExtension.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/base/PdfFileStream.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/base/PdfTokenizer.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/base/PdfDataType.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/base/PdfFilter.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/base/PdfReference.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/base/PdfRefCountedInputDevice.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/base/PdfEncodingFactory.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/base/PdfString.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/base/PdfWriter.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/base/PdfEncoding.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/base/PdfImmediateWriter.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/base/PdfArray.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/base/PdfStream.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/base/PdfDictionary.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/base/podofoapi.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/base/PdfRect.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/base/PdfData.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/base/PdfDate.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/base/PdfError.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/base/PdfMemStream.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/base/PdfOutputStream.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/base/PdfColor.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/base/PdfCompilerCompat.h.cpp
${PoDoFo_SOURCE_DIR}/cib/podofo/base/PdfVersion.h.cpp
${PoDoFo_SOURCE_DIR}/cib/__zz_cib_CibPoDoFo-proxy-mgr.cpp
${PoDoFo_SOURCE_DIR}/cib/__zz_cib_CibPoDoFo-classId-repo.cpp
)

SET(PODOFO_CIB_HEADERS
${PoDoFo_SOURCE_DIR}/cib/__zz_cib_CibPoDoFo-type-converter-proxy-class.h
${PoDoFo_SOURCE_DIR}/cib/__zz_cib_CibPoDoFo-smart-ptr-detection.h
${PoDoFo_SOURCE_DIR}/cib/__zz_cib_CibPoDoFo-type-converter-proxied-class.h
${PoDoFo_SOURCE_DIR}/cib/__zz_cib_CibPoDoFo-export.h
${PoDoFo_SOURCE_DIR}/cib/__zz_cib_CibPoDoFo-ids.h
${PoDoFo_SOURCE_DIR}/cib/__zz_cib_CibPoDoFo-type-traits.h
${PoDoFo_SOURCE_DIR}/cib/__zz_cib_CibPoDoFo-type-converter-basic.h
${PoDoFo_SOURCE_DIR}/cib/__zz_cib_CibPoDoFo-smart-ptr-input.h
${PoDoFo_SOURCE_DIR}/cib/__zz_cib_CibPoDoFo-class-proxy-detection.h
${PoDoFo_SOURCE_DIR}/cib/__zz_cib_CibPoDoFo-mtable-helper.h
${PoDoFo_SOURCE_DIR}/cib/__zz_cib_CibPoDoFo-type-converter-smart-ptr.h
${PoDoFo_SOURCE_DIR}/cib/__zz_cib_CibPoDoFo-type-converter-std-function.h
${PoDoFo_SOURCE_DIR}/cib/__zz_cib_CibPoDoFo-delegate-helper.h
${PoDoFo_SOURCE_DIR}/cib/__zz_cib_CibPoDoFo-type-converters.h
${PoDoFo_SOURCE_DIR}/cib/__zz_cib_CibPoDoFo-decl.h
${PoDoFo_SOURCE_DIR}/cib/__zz_cib_CibPoDoFo-class-types.h
${PoDoFo_SOURCE_DIR}/cib/__zz_cib_CibPoDoFo-type-converter-base.h
${PoDoFo_SOURCE_DIR}/cib/__zz_cib_CibPoDoFo-proxy-mgr.h
${PoDoFo_SOURCE_DIR}/cib/__zz_cib_CibPoDoFo-std-function-converter-base.h
${PoDoFo_SOURCE_DIR}/cib/__zz_cib_CibPoDoFo-class-down-cast.h
${PoDoFo_SOURCE_DIR}/cib/__zz_cib_CibPoDoFo-type-converter-function-object.h
${PoDoFo_SOURCE_DIR}/cib/__zz_cib_CibPoDoFo-value-types.h
${PoDoFo_SOURCE_DIR}/cib/__zz_cib_CibPoDoFo-internal.h
${PoDoFo_SOURCE_DIR}/cib/__zz_cib_CibPoDoFo-generic.h
${PoDoFo_SOURCE_DIR}/cib/__zz_cib_CibPoDoFo-mtable.h
${PoDoFo_SOURCE_DIR}/cib/__zz_cib_stl-helpers/__zz_cib_vector-reverse_iterator.h
${PoDoFo_SOURCE_DIR}/cib/__zz_cib_stl-helpers/__zz_cib_bidirectional_reverse_iterator.h
${PoDoFo_SOURCE_DIR}/cib/__zz_cib_stl-helpers/__zz_cib_bidirectional_iterator.h
${PoDoFo_SOURCE_DIR}/cib/__zz_cib_stl-helpers/__zz_cib_vector-iterator.h
${PoDoFo_SOURCE_DIR}/cib/__zz_cib_CibPoDoFo-class-helper.h
)

SET(PODOFO_EXP_SOURCES
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_PoDoFo.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/podofo-base.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfFontConfigWrapper.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfExtGState.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfFontCache.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfPagesTreeCache.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfAction.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfFontMetricsBase14.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfAcroForm.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfPage.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfPagesTree.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfFontMetricsFreetype.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfPainter.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfCMapEncoding.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfDifferenceEncoding.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfShadingPattern.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfImage.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfHintStream.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfFontMetrics.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfDocument.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfFontType3.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfNamesTree.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfFontType1Base14.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfFunction.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfFileSpec.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfSignOutputDevice.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfField.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfStreamedDocument.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfOutlines.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfElement.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfFontCID.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfAnnotation.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfPainterMM.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfSignatureField.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfDestination.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfIdentityEncoding.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfFontType1.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfTable.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfFontTrueType.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfInfo.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfFontTTFSubset.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfContents.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfFontFactory.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfFontSimple.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfFontMetricsObject.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfXObject.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfMemDocument.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfTilingPattern.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfFont.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfFontFactoryBase14Data.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfEncodingObjectFactory.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/podofo.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfObjectStreamParserObject.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfOutputDevice.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfDataType.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfFilter.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfRect.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfArray.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfName.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfFileStream.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfImmediateWriter.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfParser.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfParserObject.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfStream.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfContentsTokenizer.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfDictionary.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfString.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfObject.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfError.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfCompilerCompat.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfColor.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfExtension.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfInputStream.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfEncoding.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfVariant.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfReference.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfRefCountedInputDevice.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfEncodingFactory.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfMemoryManagement.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfWriter.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfEncrypt.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfOutputStream.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfCanvas.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfMemStream.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfLocale.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfDate.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/base/podofoapi.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfDefines.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfInputDevice.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfVersion.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/base/Pdf3rdPtyForwardDecl.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfVecObjects.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfData.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfRefCountedBuffer.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfTokenizer.cpp
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfOwnedDataType.cpp
)

SET(PODOFO_EXP_HEADERS
${PoDoFo_SOURCE_DIR}/exp/podofo/podofo-base.h
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfPainterMM.h
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfFontConfigWrapper.h
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfIdentityEncoding.h
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfPage.h
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfFontTTFSubset.h
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfAnnotation.h
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfDocument.h
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfAcroForm.h
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfFontCID.h
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfSignOutputDevice.h
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfFontFactoryBase14Data.h
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfDifferenceEncoding.h
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfSignatureField.h
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfStreamedDocument.h
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfFontMetricsObject.h
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfOutlines.h
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfPagesTree.h
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfTilingPattern.h
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfShadingPattern.h
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfPagesTreeCache.h
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfEncodingObjectFactory.h
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfFontFactory.h
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfNamesTree.h
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfPainter.h
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfField.h
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfFunction.h
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfFontMetrics.h
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfFontSimple.h
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfFileSpec.h
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfInfo.h
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfHintStream.h
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfFontTrueType.h
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfFontMetricsBase14.h
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfFont.h
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfTable.h
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfCMapEncoding.h
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfFontType1.h
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfImage.h
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfContents.h
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfFontType3.h
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfDestination.h
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfExtGState.h
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfAction.h
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfElement.h
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfMemDocument.h
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfXObject.h
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfFontCache.h
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfFontType1Base14.h
${PoDoFo_SOURCE_DIR}/exp/podofo/doc/PdfFontMetricsFreetype.h
${PoDoFo_SOURCE_DIR}/exp/podofo/podofo.h
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfCanvas.h
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfParserObject.h
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfEncoding.h
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfObjectStreamParserObject.h
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfMemStream.h
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfVersion.h
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfTokenizer.h
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfExtension.h
${PoDoFo_SOURCE_DIR}/exp/podofo/base/podofoapi.h
${PoDoFo_SOURCE_DIR}/exp/podofo/base/Pdf3rdPtyForwardDecl.h
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfImmediateWriter.h
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfVariant.h
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfInputDevice.h
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfWriter.h
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfVecObjects.h
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfOutputDevice.h
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfFileStream.h
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfStream.h
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfColor.h
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfOutputStream.h
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfRect.h
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfString.h
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfDate.h
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfEncrypt.h
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfContentsTokenizer.h
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfDictionary.h
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfReference.h
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfInputStream.h
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfEncodingFactory.h
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfMemoryManagement.h
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfOwnedDataType.h
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfLocale.h
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfName.h
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfArray.h
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfDefines.h
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfCompilerCompat.h
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfRefCountedInputDevice.h
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfFilter.h
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfRefCountedBuffer.h
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfError.h
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfParser.h
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfDataType.h
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfData.h
${PoDoFo_SOURCE_DIR}/exp/podofo/base/PdfObject.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class284.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class293.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_CibPoDoFo-type-converter-proxy-class.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class262.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class278.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_CibPoDoFo-smart-ptr-detection.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_CibPoDoFo-internal-proxy.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_CibPoDoFo-type-converter-proxied-class.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class300.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class308.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_CibPoDoFo-ids.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class271.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class294.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class317.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class287.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class310.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class307.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class269.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class273.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_CibPoDoFo-type-traits.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class275.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_bidirectional_iterator-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_CibPoDoFo-type-converter-basic.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_vector-iterator-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_CibPoDoFo-def.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class296.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_CibPoDoFo-smart-ptr-input.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_vector-reverse_iterator-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_CibPoDoFo-class-proxy-detection.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class306.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class324.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/vector-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class277.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class268.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class330.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class282.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class322.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class318.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class260.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class266.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class280.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_CibPoDoFo-import.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_vector-iterator-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/list-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_bidirectional_reverse_iterator-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/podofo-base-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/podofo-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfFontCID-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfInfo-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfFontFactoryBase14Data-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfInfo-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfDocument-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfPainterMM-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfStreamedDocument-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfFontType1Base14-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfAcroForm-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfFontTrueType-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfElement-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfCMapEncoding-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfShadingPattern-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfMemDocument-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfImage-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfFontTrueType-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfContents-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfHintStream-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfIdentityEncoding-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfDifferenceEncoding-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfHintStream-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfFontTTFSubset-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfTable-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfPainter-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfSignatureField-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfEncodingObjectFactory-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfFontTTFSubset-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfFontMetricsFreetype-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfElement-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfSignOutputDevice-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfOutlines-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfMemDocument-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfFontSimple-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfFontMetricsObject-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfPagesTree-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfField-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfFontCache-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfDestination-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfFont-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfFontSimple-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfField-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfFontType1Base14-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfOutlines-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfEncodingObjectFactory-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfTable-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfPagesTreeCache-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfStreamedDocument-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfFontMetrics-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfTilingPattern-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfFontFactory-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfCMapEncoding-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfFontType1-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfPagesTreeCache-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfContents-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfFontCache-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfIdentityEncoding-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfFunction-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfFontConfigWrapper-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfPagesTree-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfXObject-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfAnnotation-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfFontMetricsBase14-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfTilingPattern-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfSignOutputDevice-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfDifferenceEncoding-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfNamesTree-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfDocument-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfFileSpec-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfFontFactoryBase14Data-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfFontCID-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfFontMetricsBase14-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfFontType3-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfDestination-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfFontType1-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfFileSpec-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfNamesTree-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfAnnotation-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfPage-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfXObject-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfFontType3-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfFontMetricsFreetype-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfFontConfigWrapper-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfPainterMM-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfFontFactory-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfPage-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfShadingPattern-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfAcroForm-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfAction-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfPainter-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfFontMetricsObject-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfImage-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfExtGState-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfSignatureField-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfFunction-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfAction-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfExtGState-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfFont-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/doc/PdfFontMetrics-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/podofo-base-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/podofo-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfMemStream-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfImmediateWriter-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfTokenizer-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfContentsTokenizer-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfParser-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfObject-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfMemoryManagement-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfContentsTokenizer-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfString-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfDictionary-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfObjectStreamParserObject-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfWriter-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfCompilerCompat-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfStream-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfMemoryManagement-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfOutputStream-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfEncrypt-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfObjectStreamParserObject-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfError-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfArray-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfVariant-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfEncrypt-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfInputStream-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfVersion-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfInputStream-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfImmediateWriter-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfOutputDevice-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfData-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfOutputDevice-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/Pdf3rdPtyForwardDecl-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfData-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfObject-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfDataType-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfCompilerCompat-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfDate-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfEncoding-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfVariant-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfParserObject-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfColor-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfRect-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfString-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfRect-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfRefCountedInputDevice-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfVersion-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfName-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfLocale-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfName-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfEncoding-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfVecObjects-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfVecObjects-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfRefCountedBuffer-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfEncodingFactory-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfReference-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfOwnedDataType-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfParserObject-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/podofoapi-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfFileStream-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfWriter-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfEncodingFactory-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/podofoapi-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfColor-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfDefines-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfDataType-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfArray-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfFilter-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfParser-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfExtension-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfReference-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfCanvas-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfDictionary-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfInputDevice-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfRefCountedInputDevice-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfInputDevice-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfOutputStream-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfError-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfDate-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfFileStream-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfStream-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/Pdf3rdPtyForwardDecl-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfMemStream-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfExtension-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfFilter-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfCanvas-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfDefines-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfLocale-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfOwnedDataType-postdef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfTokenizer-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/podofo/base/PdfRefCountedBuffer-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class328.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class264.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class259.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class332.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class292.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class298.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class312.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class286.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class309.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_CibPoDoFo-mtable-helper.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class285.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_CibPoDoFo-type-converter-smart-ptr.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_CibPoDoFo-type-converter-std-function.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class272.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_bidirectional_iterator-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class329.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class265.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class299.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class257.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class305.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_CibPoDoFo-type-converters.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class326.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class270.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class320.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_CibPoDoFo-decl.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class323.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class319.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class288.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class301.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_CibPoDoFo-class-types.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class316.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class313.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_CibPoDoFo-type-converter-base.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class331.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class258.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class311.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class289.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class283.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class297.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_CibPoDoFo-class-internal-def.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_CibPoDoFo-std-function-converter-base.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class304.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class263.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class314.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class267.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class327.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_CibPoDoFo-type-converter-function-object.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class290.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class291.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class303.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class274.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class281.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class295.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_CibPoDoFo-generic.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class325.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_CibPoDoFo-mtable.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class321.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class279.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_vector-reverse_iterator-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class315.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_bidirectional_reverse_iterator-predef.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_CibPoDoFo-class-helper.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class276.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_internal/__zz_cib_Class302.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_stl-helpers/__zz_cib_vector-reverse_iterator.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_stl-helpers/__zz_cib_bidirectional_reverse_iterator.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_stl-helpers/__zz_cib_bidirectional_iterator.h
${PoDoFo_SOURCE_DIR}/exp/__zz_cib_stl-helpers/__zz_cib_vector-iterator.h
)

